### ISSUE TITLE
Problems when trying to use TestRail.

### ISSUE THREAD

**Issue by DerekHunterIcon** [zoosk/testrail-client#22]
Hey guys, we've been using this for a while and we started having problems with in the last few days. 

When we try to use this apart of our project  we get this error :

"Unhandled loader error: 8 (null) Newtonsoft.Json, Version=8.0.0.0 Culture=neutral ..."

Then it dumps gbd stacktrace information at us. I was looking at the project and it looks like the .csproj file has a reference to that version of Newtonsoft.Json.  From what I could tell that version never existed in the public. Any thoughts on the issue would be greatly appreciated. 

I'm going to head home for the day but i'll look into more tomorrow.

Edit: We're using mono 4.0

Thanks!
-Derek

**Comment by Astro03** [comment]
If you look at the 2 lines below  the line you posted, you'll see that "specific version" is set to false and that the actual version is 8.0.3 (released 2016.03.14 according to https://www.nuget.org/packages/newtonsoft.json/). 

I'm assuming the error you are seeings stems from the fact that upgraded your JSON package on 9.0.1 on 2016.06.22. 

Thus the main issue is... the package is looking for a JSON which is 8.X.X and not the 9.X.X which you downloaded. 

I'll try to upgrade the packages in test rail and redeploy within the next week. 

thanks,
ASTRO

**Comment by DerekHunterIcon** [comment]
Thats exactly what happened somebody updated the json package, we reverted and now its up and running. Thanks!

**Comment by Astro03** [comment]
glad i can be of assistance.

**Comment by Astro03** [comment]
updated with https://www.nuget.org/packages/TestRail/ 
now you can use 9.0.1
