### ISSUE TITLE
Elapsed Time in test result always update default value(14913w 3h).

### ISSUE THREAD

**Issue by karthim20** [zoosk/testrail-client#25]
![default](https://user-images.githubusercontent.com/3843043/27287014-f133c198-551f-11e7-8039-76c150eff68f.PNG)
![afterremovingticks](https://user-images.githubusercontent.com/3843043/27287032-08f9e62c-5520-11e7-8bc5-77efd682bd25.PNG)

Elapsed Time in test result always update default value(14913w 3h).

Fix:
Remove (.Ticks) from TestRail.Types.Result.cs class. I verified this and its working as expected. Since I don't have the permission, am creating this as an issue.

**Comment by Astro03** [comment]
You can create a PR.  Thx.  

Ciao,
ASTRO

**Comment by Astro03** [comment]
@karthim20  can you tell me if branch "elapsed_fix" fixes your issue?

**Comment by karthim20** [comment]
@Astro03  Will try and let you know

**Comment by Astro03** [comment]
i believe with the latest release, this should be fixed.
