### ISSUE TITLE
Different number of testResultIds by GetResults method

### ISSUE THREAD

**Issue by thonypr** [zoosk/testrail-client#27]
Hi!

First of all, thanks for convenien api-client for testrail - you are cool, guys!

But ive met some problem here...
I've managed to write simple code that get all the results from all the runs in testrail.
So its smth like
get projects
foreach project
      get runs
      foreach run
              get tests
              for each test
                     get results
                     log them into file

So, Ive run that code 2 times and got different responses.
That would not be a problem as soon as there could be new records in TR, but the amount of records decreased and its for sure that noone has deleted anything in Testrail.

so, this is the messages from telegram-bot that logs it out for me:

linksBot, [29.06.17 21:03]
start=29.06.2017 20:09:11 end = 29.06.2017 21:03:29 count= 15635 defCount= 909

linksBot, [30.06.17 11:37]
start=30.06.2017 10:37:38 end = 30.06.2017 11:37:23 count= 14888 defCount= 897

as you can see - sum of defCount and count differs

Could you please provide me with more details on the work of the method GetResults?
It might help me to handle that situation - maybe there are some hiddne filters or smth?..
What could be the reason for Test to not include it into a result query?

Thanks a lot in advance!

Thony

**Comment by Astro03** [comment]
Hi @thonypr 

For troubleshooting, i would first try to get the projects.. then make sure the number of projects and the projects are equal.. then i would just compare the runs..  and etc.. 

The api literally just calls the get method on testrail and parses that. so it should be simple. We do nothing truly difficult in the code. 

http://docs.gurock.com/testrail-api2/reference-results

**Comment by thonypr** [comment]
Looks like Ive figured out what was going on with the different sums - I was using Parallel.ForEach - maybe there were some problems because of it.
On the other side, with simple foreach there are ~20k records and it seems legit.

But still, there is a slight issue with GetResults...

In the last comment Ive mentioned defCount - its the count of "defectives" - theese are tests which for some reason dont give their results but they do have results.
Ive attached 2 pictures for explaining - there is a test with Id = 5067627 , and on the postman.png you can see that it exists and testrail has a result for it.
But in vs.png you can see that simple call for GetResults(5067627) throws an exception. Also, for proving correct connection to testrail there is a test with ID = 4532207 that has results and there are no exceptions for it.

So, the problem is that for some reasons some tests are not appliable for GetResults method :(

Can you help me with that, please?
![postman](https://user-images.githubusercontent.com/9746605/27816089-f27b7dc0-6091-11e7-9faa-0ac4914442d9.PNG)
![vs](https://user-images.githubusercontent.com/9746605/27816090-f27c9a34-6091-11e7-9010-fc5f5d314fb3.PNG)

**Comment by Astro03** [comment]
I currently don't have a machine setup with code but i think I know what is
going on.

The exception is states it. Basically, we are getting something from the
json and are trying to convert it and put it into the Object. The
conversion is not working. I would try stepping into the code and seeing
exactly where the conversion is not working.

Once you find that, you can create a PR for it and I'll accept it. :)

Sorry I can't be more helpful.

thanks,
ASTRO

**Comment by Astro03** [comment]
it throws because of the timespan field. I'll fix it.

**Comment by thonypr** [comment]
Oh great!
Sorry, I've had no chance to answer to your last comment

**Comment by Astro03** [comment]
@thonypr  can you check the branch `elapsed_fix` fixes your issue??

**Comment by thonypr** [comment]
I'm so sorry, I was pretty jammed recently.
I will try to do it until Monday 17th July

**Comment by thonypr** [comment]
Im afraid that problem is still here - ive downloaded elapsed_fix and tried to run it.
But here is the problem:
![image](https://user-images.githubusercontent.com/9746605/28339317-73f0175c-6c14-11e7-9275-d1555f0beb38.png)
Exception thrown at the row:
TestRailClient testrail = new TestRailClient(baseUrl, login, pass);
            var res = testrail.GetResults(5067627);

**Comment by Astro03** [comment]
Yeah, if you look at the branch i created, that file is different than the one you have shown.. thus you're usin the wrong branch.

https://github.com/zoosk/testrail-client/blob/elapsed_fix/TestRail/Types/Result.cs#L72

**Comment by Astro03** [comment]
@thonypr  - I'm pretty sure i can close this issue. Please reopen if problem still exists.
