### ISSUE TITLE
Delete Run is not supported?

### ISSUE THREAD

**Issue by sharique123** [zoosk/testrail-client#37]

**Comment by fushinoryuu** [comment]
I created pull request #39, hopefully they merge it soon and release the new version.

**Comment by MaxZoosk** [comment]
@fushinoryuu - I will try to take a look today.

**Comment by fushinoryuu** [comment]
@MaxZoosk It looks like the pull request was merged in, can someone please release the new version and push it to Nuget?

**Comment by MaxZoosk** [comment]
@fushinoryuu I am not setup to be able to do this and we have a lot of people on vacation, but I am trying to track down a way to get it pushed. Will update when I have more info.

**Comment by MaxZoosk** [comment]
Sorry for the long delay @fushinoryuu. I had to do quite a bit of running around to gather everything necessary to push to NuGet but we have it now and should update today or tomorrow.
