### ISSUE TITLE
Question on AddResultForCase()

### ISSUE THREAD

**Issue by Lecale** [zoosk/testrail-client#40]
Hi. I am trying out your project, and I find one method call is never working.

```
TestRailClient trc = new TestRailClient(...)
trc.AddResultForCase(runID, (ulong)8917043, ResultStatus.Passed, "AutomationTest"); //No update
trc.AddResult((ulong)8917044, ResultStatus.Passed, "AutomationTest#2"); // Is updated
```

The runID exists, it is valid, so what's going wrong. Did you ever have some issue like this, or do you know what the issue might be.

**Comment by Astro03** [comment]
Have you tried walking through the code and seeing  if we're updating it correctly? 

I actually no longer have a set up and can't run this anymore.

**Comment by Lecale** [comment]
Well I took a look through the code, and realised my mistake. (Thanks!) I mixed up CaseID and TestID. (Damn)
