### ISSUE TITLE
AddCase fail with 400 bad request 

### ISSUE THREAD

**Issue by devheroo** [zoosk/testrail-client#41]
I am using version 2.0.3 and I am getting this exception when calling AddCase method:
`System.Exception: System.Net.WebException: The remote server returned an error: (400) Bad Request.`
code :
`var caseResult = client.AddCase(42411, "Test.UnitTest1.Test1");`

any advise ?
Thanks

**Comment by Astro03** [comment]
I would try the request directly to  your testrail through the api and see if it works that way. IF it does, then there is something wrong with the SDK, but i suspect it's the usage.

**Comment by devheroo** [comment]
Thanks, I will try testrail API directly and see what happens.

**Comment by devheroo** [comment]
I found the issue with the help of fiddler , some custom fields were set to be required , testrail API will return an error message about this as below :
![image](https://user-images.githubusercontent.com/17187711/55168861-a4231f00-5141-11e9-9dcb-094aa6de6a10.png)

it will be great if this client will capture the actual return message from testrail API also.

Thanks

**Comment by Astro03** [comment]
Sure, if you wnat to put a PR here, i would gladly look at it. 

I haven't touched this code in a long time and i no longer have a testrail setup at home.

**Comment by fushinoryuu** [comment]
This should have been fixed after #46 was merged in.

@Astro03 can you please close this issue?

**Comment by cwood119** [comment]
Just wanted to say thank you to @devheroo for raising this issue 3 years ago. I recently ran into the same thing on version 3.2.1. My request was returning a generic 400 with a non-helpful stack trace, and I was at a loss until I ran into this thread.
