### ISSUE TITLE
No way to get all runs with >250 in a project

### ISSUE THREAD

**Issue by itsdrewmiller** [zoosk/testrail-client#43]
According to the docs http://docs.gurock.com/testrail-api2/reference-runs an offset parameter is required to get more than the 250 most recent items.

**Comment by Astro03** [comment]
Oh okay, If you create a PR and test it, i will gladly create a new library.

**Comment by itsdrewmiller** [comment]
I didn't end up getting around to any other changes, so if you want to cut a release don't wait for me!

**Comment by Astro03** [comment]
@itsdrewmiller Ah okay. I will do it after I get off work.
