### ISSUE TITLE
GetSections suiteID should be optional

### ISSUE THREAD

**Issue by fvaillancourt** [zoosk/testrail-client#47]
In testrail documentation it states that the suiteID parameter to get sections is optional but there is no way to call GetSections without it using the library.

**Comment by Astro03** [comment]
@fvaillancourt  Could you send a PR with the changes you require?

**Comment by fredericvaillancourt** [comment]
@Astro03 Pull request has been made (9 days ago). Any idea when it will be merged?

**Comment by Astro03** [comment]
Sorry, I'll do it tonight.

**Comment by Astro03** [comment]
Updated and released as https://www.nuget.org/packages/TestRail/2.0.5
