### ISSUE TITLE
AddRun should return the same payload as the TestRail API

### ISSUE THREAD

**Issue by MaximeBrodeur** [zoosk/testrail-client#52]
According to this documentation: 
http://docs.gurock.com/testrail-api2/reference-runs

The add_run api return the exact same thing as get_run, but the testrail_client library only returns the ID. This force us to do a second api call to get the whole test run, which is time consuming.

**Comment by fushinoryuu** [comment]
This should have been fixed after #46 was merged in. 

@Astro03 can you please close this issue?
