### ISSUE TITLE
AddRun method should be updated

### ISSUE THREAD

**Issue by BykovAndrii** [zoosk/testrail-client#54]
After August update it's impossible to add a new run via AddRun() method if there is no milestone in project. Earlier it was possible to set "0L" for milestone, but now while sending the request error "milestone_id is not a valid milestone" appears. Parameter type is "ulong", but now we need to pass null in current case. So, looks like type should be change for "ulong?" .

public CommandResult<ulong> AddRun(ulong projectID, ulong suiteID, string name, string description, ulong milestoneID, ulong? assignedToID = null, HashSet<ulong> caseIDs = null, JObject customs = null);

 Official API works fine and new run can be added by setting milestone_id to null in request or just excluding it in general.

**Comment by Astro03** [comment]
@fushinoryuu ^

**Comment by fushinoryuu** [comment]
@BykovAndrii & @Astro03: sorry about that, I will fix this as soon as possible
