### ISSUE TITLE
AddRun method requires suiteId

### ISSUE THREAD

**Issue by GitClickOk** [zoosk/testrail-client#57]
The [testrail-client](https://github.com/zoosk/testrail-client/blob/master/TestRail/TestRailClient.cs#L166) and the [TestRail API](https://www.gurock.com/testrail/docs/api/reference/runs#add_run) says the same thing:

> The ID of the test suite for the test run (optional if the project is operating in single suite mode, required otherwise).

How can I pass an optional (null) suiteId if the method requires a "ulong" (instead of a "ulong?")?

**Comment by Astro03** [comment]
Sorry, i guess we need to update this. it's just difficult for meto do it since i dont have a testrail instance to test against. 

If you create a PR and validate it, i can merge it for you

**Comment by GitClickOk** [comment]
Hey, not problem. You guys have a great project here. Sadly I'm in a hurry and I implemented by hand (using httpclient) because I needed add attachments too, then I did all without testrail-client. 

I will ask permission in my company if I can share this code with you.

**Comment by fushinoryuu** [comment]
@GitClickOk I've been thinking that we need to update the project to use http client instead of web requests.

If you're unable to update the code, I could look into it at some point.
