### ISSUE TITLE
Latest versions...

### ISSUE THREAD

**Issue by cowtrix** [zoosk/testrail-client#58]
Hello. Not sure I'm a huge fan of the last few versions that have been PR'd... 

- `ID` being changed to `Id` everywhere for no real reason, kind of a pain to change
- Authorization is completely broken (there's no `Basic` at the start of `AuthString`)
- the whole `RequestResult` thing seems like an entirely unnecessary and unwieldy layer of abstraction, seemingly to just avoid throwing exceptions and again is just a pain to change
    - Also, it straight up just doesn't deserialize a bunch of things because nobody decorated the data models with their json keys, so field names like `ProjectId` don't map to JSON tokens like `project_id`

**Comment by Astro03** [comment]
@fushinoryuu  ^

**Comment by fushinoryuu** [comment]
@cowtrix I'm sorry about the issues, I will take a look tonight and get them fixed asap.

**Comment by fushinoryuu** [comment]
Unless @cowtrix has another PR, I think you can close this issue @Astro03.

**Comment by Astro03** [comment]
FYI, it's published at https://www.nuget.org/packages/TestRail/3.1.1
